source "https://rubygems.org"

gem "infrataster", "~> 0.3.2", git: "https://github.com/trombik/infrataster.git", branch: "reallyenglish"
gem "kitchen-ansible"
gem "kitchen-sync", "~> 2.1.1", git: "https://github.com/trombik/kitchen-sync.git", branch: "without_full_path_to_rsync"
gem "kitchen-vagrant"
gem "kitchen-verifier-serverspec"
gem "kitchen-verifier-shell"
gem "rake"
gem "rspec"
gem "rubocop", "~> 0.51.0"
gem "serverspec"
gem "specinfra"
gem "test-kitchen"
